In [0]:
from pyspark import SparkConf, SparkContext
conf = SparkConf().setAppName("student-data")
sc = SparkContext.getOrCreate(conf=conf)

In [0]:
#Removing the header
rdd = sc.textFile("/FileStore/tables/StudentData.csv")
headers = rdd.first()
rdd = rdd.filter(lambda x: x!=headers)
rdd = rdd.map(lambda x: x.split(','))

In [0]:
#Number of students 
print("Total number of students: " , rdd.count())

Total number of students:  1000

In [0]:
#Total marks acheieved by males and females students
rdd2 = rdd
rdd2 = rdd2.map(lambda x: (x[1], int(x[5])))
rdd2 = rdd2.reduceByKey(lambda x,y : x+y)
rdd2.collect()

Out[45]: [('Female', 29636), ('Male', 30461)]

In [0]:
#Total number of students who failed and passed
rdd3 = rdd
passed = rdd3.filter(lambda x: int(x[5]) > 50).count()
failed = rdd3.filter(lambda x: int(x[5]) < 50).count()
print("Passed: ", passed)
print("Failed: ", failed)

Passed:  630
Failed:  356

In [0]:
#Total number of students enrolled per course
rdd4 = rdd
rdd4 = rdd4.map(lambda x: (x[3],1))
rdd4.reduceByKey(lambda x,y: x+y).collect()

Out[47]: [('DB', 157),
 ('Cloud', 192),
 ('PF', 166),
 ('MVC', 157),
 ('OOP', 152),
 ('DSA', 176)]

In [0]:
#Total marks achieved by students per course
rdd5 = rdd
rdd5 = rdd5.map(lambda x: (x[3], int(x[5])))
rdd5.reduceByKey(lambda x,y : x+y).collect()

Out[48]: [('DB', 9270),
 ('Cloud', 11443),
 ('PF', 9933),
 ('MVC', 9585),
 ('OOP', 8916),
 ('DSA', 10950)]

In [0]:
#Average marks per course

rdd6 = rdd
rdd6 = rdd6.map(lambda x: (x[3], (int(x[5]), 1) ))
rdd6 = rdd6.reduceByKey( lambda x,y : (x[0] + y[0], x[1] + y[1]))

rdd6.mapValues(lambda x: (x[0] / x[1])).collect()

Out[49]: [('DB', 59.044585987261144),
 ('Cloud', 59.598958333333336),
 ('PF', 59.83734939759036),
 ('MVC', 61.05095541401274),
 ('OOP', 58.6578947368421),
 ('DSA', 62.21590909090909)]

In [0]:
#Min and max marks achieved per course

rdd7 = rdd
rdd7 = rdd7.map(lambda x: (x[3], int(x[5])))
print("Maximum: ", rdd7.reduceByKey(lambda x,y: x if x > y else y).collect())
print("Minimum: ", rdd7.reduceByKey(lambda x,y: x if x < y else y).collect())

Maximum:  [('DB', 98), ('Cloud', 99), ('PF', 99), ('MVC', 99), ('OOP', 99), ('DSA', 99)]
Minimum:  [('DB', 20), ('Cloud', 20), ('PF', 20), ('MVC', 22), ('OOP', 20), ('DSA', 20)]

In [0]:
#Show average males and females age
rdd8 = rdd
rdd8 = rdd8.map( lambda x: ( x[1] , ( int(x[0]), 1 ) ) )
rdd8 = rdd8.reduceByKey(lambda x,y: ( x[0] + y[0], x[1] + y[1] )  )
rdd8.mapValues(lambda x: x[0]/x[1]).collect()

Out[60]: [('Female', 28.489021956087825), ('Male', 28.52304609218437)]